[workspace]
members = [ 
    #token-escrow,
    "token-escrow/native/program",
    "token-escrow/anchor/programs/*",
    #token-vault,
    "token-vault/anchor/programs/*",
    "token-vault/native/program"
]
resolver = "2"

[profile.release]
overflow-checks = true
