[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aloo = "D4s8q3C8b7GpMMJ12TyFNT7miiHyb7fQpPt1mJQZQG11"
anchor_vault = "9wxWDkCXccoaiGXWBphS2fsB6yLjtQ622sLeWGS9V8u1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
